models.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from .app import db

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30))
    comment_text = db.Column(db.String(1000))

    def __repr__(self):
        return '<Comment {}>'.format(self.name) 

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()

def create_app():
    """
    :return: Flask app
    """
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    migrate = Migrate(app, db)
    db.init_app(app)

    from .views import main
    app.register_blueprint(main)

    from .models import Comment

    return app

views.py
from flask import (
    Blueprint, 
    render_template, 
    request, 
    redirect, 
    url_for)
from .app import db
from .models import Comment

main = Blueprint('main', __name__)

@main.route('/')
def index():
    comments = Comment.query.all()
    return render_template('index.html', comments=comments)

@main.route('/sign', methods=['GET', 'POST'])
def sign():
    if request.method == 'POST':
        name = request.form.get('name')
        comment = request.form.get('comment')

        new_comment = Comment(name=name, comment_text=comment)
        db.session.add(new_comment)
        db.session.commit()
        
        return redirect(url_for('main.index'))
    return render_template('sign.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet"> 
    
    {% block css %}{% endblock %}

  </head>

  <body>
    {% block body %}{% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Guest Book{% endblock %}

{% block css %}
<!-- Bootstrap theme -->
<link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{{ url_for('static', filename='css/theme.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="container theme-showcase" role="main">

    <div class="jumbotron">
        <h1>Guest Book</h1>
        <a type="button" class="btn btn-link" href="{{ url_for('main.sign') }}">Sign the Guest Book</a>
    </div>

    {% for comment in comments %}
    <div class="page-header">
        <h1>{{ comment.name }}</h1>
    </div>
    <div class="well">
        <p>{{ comment.comment_text }}</p>
    </div>
    {% endfor %}

</div> <!-- /container -->
{% endblock %}

templates/sign.html
{% extends 'base.html' %}

{% block title %}Sign the Guest Book{% endblock %}

{% block css %}
<!-- Custom styles for this template -->
<link href="{{ url_for('static', filename='css/sign.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="container">

    <form class="form-signin" method="POST" action="{{ url_for('main.sign') }}">
        <h2 class="form-signin-heading">Sign the Guest Book</h2>
        <div class="form-group">
            <label for="inputName" class="sr-only">Name</label>
            <input type="text" id="inputName" name="name" class="form-control" placeholder="Name" required autofocus>
        </div>
        <div class="form-group">
            <label for="comment" class="sr-only">Comment:</label>
            <textarea class="form-control" name="comment" rows="5" id="comment" placeholder="Comment"
                required></textarea>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign</button>
    </form>

</div> <!-- /container -->
{% endblock %}